apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: fotso-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fotso-apache
  template:
    metadata:
      labels:
        app: fotso-apache
    spec:
      containers:
      - name: fotso-apache-container
        image: fotso2024/fotso_apache_image:v1.0.1
        ports:
        - containerPort: 80
